#!/bin/bash
# Copyright (C) 2008 Vlideshow Inc., All Rights Reserved
# http://www.theyard.net/ or http://www.vlideshow.com/
#
# This library is free software; you can redistribute it and/or modify it under the 
# terms of the GNU Lesser General Public License as published by the Free Software 
# Foundation; either version 2.1 of the License, or (at your option) any later 
# version. 
# 
# This library is distributed in the hope that it will be useful, but WITHOUT ANY 
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public License along 
# with this library; if not, write to the Free Software Foundation, Inc., 
# 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA 
#

usage0="USAGE:"
usage1="$0 <number-of-tests>"

if [ "$1" = "" ]
then
    echo ERROR: missing test count
    echo 
    echo "  " $usage0
    echo "     " $usage1
    echo 
    exit 1
fi

ant compile-tests
for ((i=0; i < $1; ++i)); do flash-player bin/test/fity.swf ; done
