package io.antmedia.rest.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(value="SslConfigurationResult", description="Holds data of ssl configuration result after command output returned by ssl script.")

public class SslConfigurationResult {
    /**
     * Gives information about the operation.
     * If it is true, operation is successful
     * if it is false, operation is failed
     */
    @ApiModelProperty(value = "the result of the operation")
    private boolean success = false;

    /**
     * Message may be filled error or information.
     * It is filled with error when success field
     * is false so that developer may understand what the problem is.
     * It is filled with information if user makes a request, it returns success as true with additional information
     */
    @ApiModelProperty(value = "the message of the operation result")
    private String message;

    /**
     * If operation is about adding a record, then the below field have the id of the record
     */
    @ApiModelProperty(value = "ams cloud domain generated by ssl script")
    private String amsCloudDomain;


    public SslConfigurationResult(boolean success, String message) {
        this.success = success;
        this.message = message;
    }

    public boolean isSuccess() {
        return success;
    }

    public void setSuccess(boolean success) {
        this.success = success;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getAmsCloudDomain() {return amsCloudDomain;}

    public void setAmsCloudDomain(String amsCloudDomain) {this.amsCloudDomain = amsCloudDomain;}





}
